### ISSUE TITLE
Execution failed for task ':compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by felipemattar** [jlopezcur/GodotGooglePlayGameServices#11]
Any solution for this?

Task :compileDebugJavaWithJavac
/Users/felipemattar/Documents/TRABALHOS/GAMES/Custom export/Godot 2.1.5 stable/godot-2.1/modules/gpgs/android/gpgs/Leaderboards.java:79: error: cannot find symbol
                                        activity.startActivityForResult(intent, REQUEST_LEADERBOARD);
                                                                                            ^
  symbol: variable intent
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by felipemattar** [comment]
Something was wrong with the module files, I just downloaded again and its working now, thanks.

**Comment by richardbonneau** [comment]
@felipemattar  Can you tell us exactly what was wrong with your module files?
