### ISSUE TITLE
gpgs keeps try to login even without internet

### ISSUE THREAD

**Issue by ghost** [jlopezcur/GodotGooglePlayGameServices#4]
Well, the sigin works perfectly but when you haven't any connections from internet and try to sigin the game shows the google play games' logo and keep trying to sigin, the logo appears many times in loop.

**Comment by ghost** [comment]
I solved the bug. In the file Client.java, at the method resolveConnectionFailure, just remove the follow code:
```
if (errorCode == ConnectionResult.INTERNAL_ERROR) {
  googleApiClient.connect();//comentei esta linha
}
```
This code cause to try reconnect to google play game services, even when nothing can be do to connect, because not have internet.

**Comment by ghost** [comment]
Reopen to someone see the bug and make a pull request hehe

**Comment by cbrhex** [comment]
Fixed
